### ISSUE TITLE
tox py38 failure

### ISSUE THREAD

**Issue by jayvdb** [thombashi/thank-you-stars#3]
One path for the problem is in upstream tabledata -> typepy.  Below is DataProperty - I havent found which dependency drags that in yet.
```
> tox -e py38
GLOB sdist-make: /home/jayvdb/projects/python/thank-you-stars/setup.py
py38 create: /home/jayvdb/projects/python/thank-you-stars/.tox/py38
py38 installdeps: pytest
py38 inst: /home/jayvdb/projects/python/thank-you-stars/.tox/.tmp/package/1/thank-you-stars-0.0.8.zip
py38 testmon: setting TESTMON_DATAFILE=/home/jayvdb/projects/python/thank-you-stars/.tox/py38/.testmondata
py38 installed: appconfigpy==0.4.2,attrs==19.3.0,certifi==2019.11.28,chardet==3.0.4,colorama==0.4.3,DataProperty==0.47.0,DateTimeRange==0.6.1,Deprecated==1.2.7,idna==2.9,Logbook==1.5.3,mbstrdecoder==0.8.4,more-itertools==8.2.0,msgfy==0.0.7,packaging==20.3,pathvalidate==0.29.1,pluggy==0.13.1,py==1.8.1,PyGithub==1.47,PyJWT==1.7.1,pyparsing==2.4.6,pytablewriter==0.50.0,pytest==5.4.1,python-dateutil==2.8.1,pytz==2019.3,requests==2.23.0,retryrequests==0.0.3,simplejson==3.17.0,six==1.14.0,subprocrunner==0.17.2,tabledata==1.1.1,thank-you-stars==0.0.8,tqdm==4.44.1,typepy==1.0.0,urllib3==1.25.8,wcwidth==0.1.9,wrapt==1.12.1
py38 run-test-pre: PYTHONHASHSEED='1184530578'
py38 run-test: commands[0] | python setup.py test
running pytest
Searching for typepy[datetime]<1.0.0,>=0.6.0
Reading https://pypi.org/simple/typepy/
Downloading https://files.pythonhosted.org/packages/54/e8/e11b753cced190dd2e3decc1697a5fed3325e94f4e9c4ef20ff7936948ec/typepy-0.6.6-py2.py3-none-any.whl#sha256=1cc1c8a96e4e78f9487b190627dec15ca579dbf5c929ce8035878b0f6ba31f40
Best match: typepy 0.6.6
Processing typepy-0.6.6-py2.py3-none-any.whl
Installing typepy-0.6.6-py2.py3-none-any.whl to /home/jayvdb/projects/python/thank-you-stars/.eggs

Installed /home/jayvdb/projects/python/thank-you-stars/.eggs/typepy-0.6.6-py3.8.egg
Traceback (most recent call last):
  File "setup.py", line 48, in <module>
    setuptools.setup(
  File "/home/jayvdb/projects/python/thank-you-stars/.tox/py38/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/jayvdb/projects/python/thank-you-stars/.eggs/pytest_runner-5.2-py3.8.egg/ptr.py", line 202, in run
    installed_dists = self.install_dists(dist)
  File "/home/jayvdb/projects/python/thank-you-stars/.eggs/pytest_runner-5.2-py3.8.egg/ptr.py", line 153, in install_dists
    orig.test.install_dists(dist), self.install_extra_dists(dist)
  File "/home/jayvdb/projects/python/thank-you-stars/.tox/py38/lib/python3.8/site-packages/setuptools/command/test.py", line 209, in install_dists
    ir_d = dist.fetch_build_eggs(dist.install_requires)
  File "/home/jayvdb/projects/python/thank-you-stars/.tox/py38/lib/python3.8/site-packages/setuptools/dist.py", line 684, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "/home/jayvdb/projects/python/thank-you-stars/.tox/py38/lib/python3.8/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (typepy 0.6.6 (/home/jayvdb/projects/python/thank-you-stars/.eggs/typepy-0.6.6-py3.8.egg), Requirement.parse('typepy[datetime]<2,>=1.0.0'), {'DataProperty'})
```

**Comment by jayvdb** [comment]
The other path is pytablewriter -> DataProperty -> typepy

**Comment by thombashi** [comment]
Thank you for your report.

Looks like one of the external dependency package (`DateTimeRange`) caused the version conflict of `typepy`.
The error fixed by the above commit.

**Comment by thombashi** [comment]
I'll close the issue.
Feel free to reopen if you still have any problems about the issue.
